# Generated by Django 4.2.5 on 2023-10-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, verbose_name='почта')),
                ('country', models.CharField(max_length=30, verbose_name='страна')),
                ('city', models.CharField(max_length=30, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('number_home', models.CharField(max_length=10, verbose_name='номер дома')),
                ('production_plant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_plant.productionplant', verbose_name='завод')),
            ],
        ),
    ]
