# Generated by Django 4.2.5 on 2023-10-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_network', '0001_initial'),
        ('contacts', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='retail_network',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retail_network.retailnetwork', verbose_name='розничная сеть'),
        ),
    ]
