# Generated by Django 4.2.5 on 2023-10-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo_trader', '0001_initial'),
        ('contacts', '0002_contact_retail_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='solo_trader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solo_trader.soletrader', verbose_name='ип'),
        ),
    ]
