# Generated by Django 4.2.5 on 2023-10-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_plant', '0002_alter_productionplant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='время создания')),
                ('debt', models.FloatField(default=0, verbose_name='задолженность')),
                ('supplier', models.ManyToManyField(to='production_plant.productionplant', verbose_name='поставщик')),
            ],
        ),
    ]
