# Generated by Django 4.2.5 on 2023-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='время создания')),
                ('debt', models.FloatField(default=0, verbose_name='задолженность')),
                ('supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='production_plant.productionplant', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'розничная сеть',
                'verbose_name_plural': 'розничные сети',
            },
        ),
    ]
