# Generated by Django 4.2.5 on 2023-10-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_plant', '0001_initial'),
        ('retail_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailnetwork',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='production_plant.productionplant', verbose_name='поставщик'),
        ),
    ]
