# Generated by Django 4.2.5 on 2023-10-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_plant', '0002_alter_productionplant_options'),
        ('retail_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailnetwork',
            options={'verbose_name': 'розничная сеть', 'verbose_name_plural': 'розничные сети'},
        ),
        migrations.RemoveField(
            model_name='retailnetwork',
            name='supplier',
        ),
        migrations.AddField(
            model_name='retailnetwork',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='production_plant.productionplant', verbose_name='поставщик'),
        ),
    ]
