# Generated by Django 4.2.5 on 2023-10-09 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail_network', '0001_initial'),
        ('production_plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoleTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='время создания')),
                ('debt', models.FloatField(default=0, verbose_name='задолженность')),
                ('supplier_pd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production_plant.productionplant', verbose_name='поставщик завод')),
                ('supplier_rt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='retail_network.retailnetwork', verbose_name='поставщик розничная сеть')),
            ],
            options={
                'verbose_name': 'Индивидуальный пердприниматель',
                'verbose_name_plural': 'Индивидуальныйе пердприниматели',
            },
        ),
    ]
