# Generated by Django 4.2.5 on 2023-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('model', models.TextField(verbose_name='модель')),
                ('release', models.DateField(verbose_name='дата выхода продукта на рынок')),
                ('production_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production_plant.productionplant', verbose_name='завод')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
