# Generated by Django 4.2.5 on 2023-10-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plant', '0001_initial'),
        ('solo_trader', '0001_initial'),
        ('retail_network', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='production_plant_prod',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retail_network_prod',
        ),
        migrations.RemoveField(
            model_name='product',
            name='solo_trader_prod',
        ),
        migrations.AddField(
            model_name='product',
            name='production_plant_prod',
            field=models.ManyToManyField(blank=True, null=True, to='production_plant.productionplant', verbose_name='завод'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_network_prod',
            field=models.ManyToManyField(blank=True, null=True, to='retail_network.retailnetwork', verbose_name='розничная сеть'),
        ),
        migrations.AddField(
            model_name='product',
            name='solo_trader_prod',
            field=models.ManyToManyField(blank=True, null=True, to='solo_trader.soletrader', verbose_name='ип'),
        ),
    ]
