# Generated by Django 4.2.5 on 2023-10-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_plant', '0002_alter_productionplant_options'),
        ('retail_network', '0001_initial'),
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retail_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='retail_network.retailnetwork', verbose_name='розничная сеть'),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production_plant.productionplant', verbose_name='завод'),
        ),
    ]
