# Generated by Django 4.2.5 on 2023-10-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='почта')),
                ('country', models.CharField(max_length=30, verbose_name='страна')),
                ('city', models.CharField(max_length=30, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('number_home', models.CharField(max_length=10, verbose_name='номер дома')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='время создания')),
            ],
            options={
                'verbose_name': 'завод',
                'verbose_name_plural': 'заводы',
            },
        ),
    ]
