# Generated by Django 4.2.5 on 2023-10-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionplant',
            options={'verbose_name': 'завод', 'verbose_name_plural': 'заводы'},
        ),
    ]
